### ISSUE TITLE
Configuration from server sync is overwritten..

### ISSUE THREAD

**Issue by mrburvall** [MusesProject/MusesClient#12]
Mainactivity line 125: dbManager.insertConnectionProperties();

**Comment by JJ** [comment]
Please try and close via commit as @unintendedbear said. It's a good
practice, and it allows everyone to see what was done to close the issue.

2015-02-04 13:37 GMT+01:00 Markus <notifications@github.com>:

> Closed #12 <https://github.com/MusesProject/MusesClient/issues/12>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MusesProject/MusesClient/issues/12#event-229998690>.
>



-- 
JJ
