### ISSUE TITLE
Login when a new sessionId is used

### ISSUE THREAD

**Issue by mrburvall** [MusesProject/MusesClient#15]
Description:
If the session Id (Cookie) changes the server will reject data with "Authentication failed"
A new login is needed at service level.

Version: Trials version 1.9, 20150217

Logs: 

Server logs:
10:24:59,020  INFO 
eu.musesproject.server.contextdatareceiver.ConnectionCallbacksImpl:206 - 
{"auth-message":"Data cannot be processed: Failed authentication
","auth-result":"FAIL","requesttype":"auth-response"}

The reason was the different sessionId sent for the data, so a new cookie 
is created. 

10:42:52,257  INFO 
eu.musesproject.server.connectionmanager.ComMainServlet:88 - 
MUSES_TAGdoPost
10:42:52,258  INFO eu.musesproject.server.connectionmanager.Helper:43 - 
Rereived Cookie: Name JSESSIONID   Value- B07C6B3690E06A47366002C086580165
10:42:52,258  INFO 
eu.musesproject.server.connectionmanager.ComMainServlet:99 - MUSES_TAG 
Info SS*, Request type:poll with data:
10:44:24,052  INFO 
eu.musesproject.server.connectionmanager.ComMainServlet:88 - 
MUSES_TAGdoPost
10:44:24,053  INFO eu.musesproject.server.connectionmanager.Helper:50 - 
Cookie created .. new request ..
10:44:24,054  INFO 
eu.musesproject.server.connectionmanager.ComMainServlet:99 - MUSES_TAG 
Info SS*, Request type:connect with data:
10:44:24,054  INFO 
eu.musesproject.server.connectionmanager.ComMainServlet:103 - Connect 
request .. Id: 9962110EC85591A54A8AF1D771C91880

Reproduce: N/A

Work Around: 
Right now username is used on server.

Solution:
Re-login when cookie/sessionId changes.

**Comment by ChristophStanik** [comment]
duplicated issue. It's related and also fixed with issue #16
