### ISSUE TITLE
Blank warning due to empty risk treatment

### ISSUE THREAD

**Issue by yasali** [MusesProject/MusesClient#20]
Description:
An empty warning is shown (no risk treatment) while disabling and enabling the screen lock in settings.

Repro:
Open Muses => Login to Muses Server => Disable screen lock => See a screen lock feedback, enable it again=> A empty risk treatment is shown

Version: 
v0.011

Work around:
Nothing yet

Solution:
Nothing yet

**Comment by szamarripa** [comment]
Added risk treatment for the rule associated to insufficient screen lock timeout.
