### ISSUE TITLE
Access denied shown to user without clicking open asset in MusesAwareApp

### ISSUE THREAD

**Issue by yasali** [MusesProject/MusesClient#23]
Description:
After infecting the system with virus, after opening public asset, access denied pop-up is shown to user without clicking open public asset again in MusesAwareApp.

Repro:
Open MusesAwareApp => open public asset => access granted => infect system with virus found => access denied pop-up comes without trying to open public asset. 

Version:
v0.011

Work around:
Nothing yet

Solution:
Nothing yet

Logs:

03-17 13:28:24.685: D/muses_workflow_test_tag(27302): UCEH - send(action, prop, context_events)
03-17 13:28:24.685: D/APP_TAG(27302): Action: virus_found
03-17 13:28:24.685: D/APP_TAG(27302): Info DC, Calling decision maker
03-17 13:28:24.685: D/APP_TAG(27302): Info DC, DecisionMaker=> Making decision with request and events
03-17 13:28:24.695: D/REQUEST_TIMEOUT(27302): 1. send: request_id: 1282214513
03-17 13:28:24.695: D/REQUEST_TIMEOUT(27302): 2. RequestTimeoutTimer constructor
03-17 13:28:24.695: D/REQUEST_TIMEOUT(27302): 3. RequestTimeoutTimer tick
03-17 13:28:24.695: D/APP_TAG(27302): Info DC, No Local decision found, Sever is ONLINE, sending user data JSON(actions,properties,contextevnts) to server
03-17 13:28:24.695: D/muses_workflow_test_tag(27302): UCEH - sendRequestToServer(JSONObject requestJSON)
03-17 13:28:24.695: D/APP_TAG(27302): ConnManager=> send data to server: {"sensor":{"CONTEXT_SENSOR_APP":{"id":"3","timestamp":1426594897782,"appversion":"1","type":"CONTEXT_SENSOR_APP","backgroundprocess":"[com.android.bluetooth]","appname":"Sweden Connectivity","packagename":"eu.musesproject.musesawareapp"},"CONTEXT_SENSOR_DEVICE_PROTECTION":{"timestamp":1426594302239,"ispasswordprotected":"true","screentimeoutinseconds":"30","isrooted":"false","musesdatabaseexists":"true","accessibilityenabled":"false","istrustedantivirusinstalled":"false","ipaddress":"192.168.44.114","type":"CONTEXT_SENSOR_DEVICE_PROTECTION"},"CONTEXT_SENSOR_CONNECTIVITY":{"mobileconnected":"false","wifiencryption":"[WPA2-PSK-CCMP][WPS][ESS]","timestamp":1426595204277,"bssid":"f8:1a:67:83:71:58","bluetoothconnected":"FALSE","wifienabled":"true","wifineighbors":"11","hiddenssid":"false","networkid":"2","type":"CONTEXT_SENSOR_CONNECTIVITY","wificonnected":"true","airplanemode":"false"},"CONTEXT_SENSOR_PACKAGE":{"id":"2","timestamp":1426594896119,"installedapps":"Sound Search for Google Play,com.google.android.ears,15;Sweden Connectivity,eu.musesproject.musesawareapp,1;Launcher,com.android.launcher,19;Package Access Helper,com.android.defcontainer,19;Exchange Services,com.google.android.exchange,500060;com.android.providers.partnerbookmarks,com.android.providers.partnerbookmarks,19;Contacts,com.android.contacts,19;Phone,com.android.phone,19;Calculator,com.android.calculator2,19;Wallet,com.google.android.apps.walletnfcrel,1019;BLE Toolbox JB,com.enzytek.bletoolbox,4;HTML Viewer,com.android.htmlviewer,19;Cell Broadcasts,com.android.cellbroadcastreceiver,19;Google Account Manager,com.google.android.gsf.login,19;Bluetooth Share,com.android.bluetooth,19;Calendar Storage,com.android.providers.calendar,19;ComClientTestTest,com.swedenconnectivity.client.test,1;Device Manager,com.google.android.apps.adm,1002;Email,com.google.android.email,500060;Downloads,com.android.providers.downloads.ui,19;Documents,com.android.documentsui,19;com.android.sharedstoragebackup,com.android.sharedstoragebackup,19;VpnDialogs,com.android.vpndialogs,19;Messaging,com.android.mms,19;MUSES,eu.musesproject.client,11;Media Storage,com.android.providers.media,700;Wifi Analyzer,com.farproc.wifi.analyzer,114;TalkBack,com.google.android.marvin.talkback,40100005;iWnnIME Keyboard (White),jp.co.omronsoft.iwnnime.ml.kbd.white,3;Certificate Installer,com.android.certinstaller,19;Clock,com.google.android.deskclock,301;Google Play services,com.google.android.gms,6776036;Currents,com.google.android.apps.currents,140231633;Setup Wizard,com.google.android.setupwizard,130;Settings,com.android.settings,19;Spring Basic Auth,org.springframework.android.basicauth,1;Street View,com.google.android.street,18102;News & Weather,com.google.android.apps.genie.geniewidget,1311;HP Print Service Plugin,com.hp.android.printservice,44;Google Search,com.google.android.googlequicksearchbox,300304160;Google Play Music,com.google.android.music,1810;Music Visualization Wallpapers,com.android.musicvis,19;Google Hindi Input,com.google.android.apps.inputmethod.hindi,463;Live Wallpaper Picker,com.android.wallpaper.livepicker,19;Memory Marksman,com.swedenconnectivity.memorymarksman,1;Google Keyboard,com.google.android.inputmethod.latin,21203;Bluetooth Low Energy,com.macdom.ble.blescanner,3;Package installer,com.android.packageinstaller,19;Google Backup Transport,com.google.android.backuptransport,19;Google Text-to-speech Engine,com.google.android.tts,210303130;Phone\/Messaging Storage,com.android.providers.telephony,19;Bubbles,com.android.noisefield,1;Maps,com.google.android.apps.maps,704001123;Cloud Print,com.google.android.apps.cloudprint,92;com.android.wallpapercropper,com.android.wallpapercropper,19;Fused Location,com.android.location.fused,19;com.android.backupconfirm,com.android.backupconfirm,19;Settings Storage,com.android.providers.settings,19;iWnn IME,jp.co.omronsoft.iwnnime.ml,22;Muses User Interface,eu.musesproject.musesclient,1;Drive,com.google.android.apps.docs,50832234;Download Manager,com.android.providers.downloads,19;Mo
03-17 13:28:26.107: D/APP_TAG(27302): ConnManager=> Server responded with JSON: {"muses-device-policy":{"files":{"action":{"request_id":-862933855,"allow":{"id":0,"condition":{"resourceType":"insensitive"},"path":"/sdcard/aware_app_remote_files/MUSES_beer_competition.pdf","riskTreatment":"Allowed"},"type":"open_asset"}},"revision":1,"schema-version":1},"requesttype":"update_policies"}
03-17 13:28:26.107: D/APP_TAG(27302): Info SS, Sending JSON to MusACS
03-17 13:28:26.107: D/muses_workflow_test_tag(27302): UCEH - receiveCb(); requestType=update_policies
03-17 13:28:26.107: D/APP_TAG(27302): Request type was update_policies
03-17 13:28:26.107: D/APP_TAG(27302): Updating polices
03-17 13:28:26.147: D/REQUEST_TIMEOUT(27302): request_id from the json is -862933855
03-17 13:28:29.691: D/REQUEST_TIMEOUT(27302): 4. RequestTimeoutTimer finished
03-17 13:28:29.691: D/REQUEST_TIMEOUT(27302): 5. handleRequestTimeout to id: 1282214513
03-17 13:28:29.691: D/REQUEST_TIMEOUT(27302): 6. removeRequestById map size: 1
03-17 13:28:29.691: D/REQUEST_TIMEOUT(27302): 7. removeRequestById map size afterwards: 0
03-17 13:28:29.701: D/APP_TAG(27302): showFeedback4
03-17 13:28:29.701: D/FeedbackActuator(27302): new feedback dialog request

**Comment by aesparcia** [comment]
Esta cuenta no est� operativa, si desea contactar conmigo h�galo a esta
direcci�n:
aesparcia@ieee.org

Si necesita contactar con alguien de S2 Grupo, h�galo a la direcci�n
mjuan@s2grupo.es

---------------------------------------------------------------------------------------------------------------------------


This account does not work, if you want to contact me, please use this
e-mail:
aesparcia@ieee.org

If you need to contact someone from S2 Group, do it to the e-mail
miguel.juan@s2grupo.es



Nota: Esta es una respuesta autom�tica a su mensaje  "Re: [MusesClient]
Access denied shown to user without clicking open asset in MusesAwareApp
(#23)" enviado el 17/03/2015 13:38:21.

Esta es la �nica notificaci�n que recibir� mientras esta persona est�
ausente.

**Comment by aesparcia** [comment]
Esta cuenta no est� operativa, si desea contactar conmigo h�galo a esta
direcci�n:
aesparcia@ieee.org

Si necesita contactar con alguien de S2 Grupo, h�galo a la direcci�n
mjuan@s2grupo.es

---------------------------------------------------------------------------------------------------------------------------


This account does not work, if you want to contact me, please use this
e-mail:
aesparcia@ieee.org

If you need to contact someone from S2 Group, do it to the e-mail
miguel.juan@s2grupo.es



Nota: Esta es una respuesta autom�tica a su mensaje  "[MusesClient] Access
denied shown to user without clicking open asset in MusesAwareApp (#23)"
enviado el 17/03/2015 13:38:22.

Esta es la �nica notificaci�n que recibir� mientras esta persona est�
ausente.
