### ISSUE TITLE
Add variable for requesting response to MusesAware Evt

### ISSUE THREAD

**Issue by mrburvall** [MusesProject/MusesClient#26]
Since a Muses aware application can either request a decision (Allow or Deny) or just inform the MUSES system of an Event, this parameter is needed.

If requestResponse = true, the MUSES aware app expects a response from MUSES.

If requestResponse = false, Then no response shall be sent.

**Comment by ChristophStanik** [comment]
SHA 26a58917584414501fc1ead2117eb158271354f3 closes this
