### ISSUE TITLE
Auto restart of MUSES shows GUI.

### ISSUE THREAD

**Issue by mrburvall** [MusesProject/MusesClient#30]
When MUSES is automatically restarted the login GUI shall not be shown.

**Comment by yasali** [comment]
Automatically restarted?, we have auto-login, what will be the use case for this?

**Comment by mrburvall** [comment]
Don't start the activity when the service restarts.

Only restart the activity when needed.

**Comment by yasali** [comment]
Fixed by not calling setContentView in MainActivity
