### ISSUE TITLE
Show MUSES icon in Status Bar

### ISSUE THREAD

**Issue by mrburvall** [MusesProject/MusesClient#34]
1. MUSES not running - no icon
2. MUSES running, not logged in

3a. MUSES running, logged in (Offline mode), no feedback

3b. MUSES running, logged in (Offline mode), feedback available

4a. MUSES running, logged in (Online mode), no feedback

4b. MUSES running, logged in (Online mode), feedback available

The service needs to inform the GUI about the "feedback" status.

**Comment by yasali** [comment]
Icon is now been implemented, and icon is changed when feedback is not clicked.

**Comment by yasali** [comment]
update icons for above when icons received from AIT
