### ISSUE TITLE
Service retsrat after every few seconds

### ISSUE THREAD

**Issue by yasali** [MusesProject/MusesClient#35]
Problem:
Service restart itself after every few seconds (3-5), which cause the tab or phone to get slow because of memory.

Repro:
Open App => Login => See pop-up click OK,=> Enable Accessibility => Open Wi-Fi Analyzer

Device:
Nexus 10 tab, Android version 4.2.2

Logs:
06-02 15:45:13.899: D/bug_test_for_login_and_autologin(30939): onCreate called in MainActivity
06-02 15:45:14.184: V/bug_test_for_login_and_autologin(30939): Registring callbacks from MainActivity!
06-02 15:45:14.189: D/bug_test_for_login_and_autologin(30939): No MUSES_SERVICE_INIT_FLAG found in preferences
06-02 15:45:14.199: D/bug_test_for_login_and_autologin(30939): MUSES_SERVICE_INIT_FLAG set in preferences
06-02 15:45:14.199: V/bug_test_for_login_and_autologin(30939): muses service started ... from MainActivity
06-02 15:45:14.214: D/bug_test_for_login_and_autologin(30939): No username-pass found in preferences
06-02 15:45:14.269: D/bug_test_for_login_and_autologin(30939): No IS_LOGGED_IN found in preferences
06-02 15:45:14.269: D/bug_test_for_login_and_autologin(30939): isloggedin: false
06-02 15:45:14.269: D/bug_test_for_login_and_autologin(30939): isloggedin in UserContextEventHandler: false
06-02 15:45:14.269: D/bug_test_for_login_and_autologin(30939): onResume called in MainActivity
06-02 15:45:14.349: D/bug_test_for_login_and_autologin(30939): MUSESBACKGROUNDService - onCreate
06-02 15:45:14.349: D/bug_test_for_login_and_autologin(30939): MUSESBACKGROUNDService - on startComment called
06-02 15:45:15.569: D/bug_test_for_login_and_autologin(30939): UCEH - autoLogin()
06-02 15:45:15.569: D/bug_test_for_login_and_autologin(30939): cannot auto login
06-02 15:45:33.349: D/bug_test_for_login_and_autologin(30939): IS_LOGGED_IN set in preferences with value: true
06-02 15:45:33.349: V/bug_test_for_login_and_autologin(30939): login success in, updating login
06-02 15:45:54.509: D/bug_test_for_login_and_autologin(30939): onResume called in MainActivity
06-02 15:46:10.209: D/bug_test_for_login_and_autologin(32004): MUSESBACKGROUNDService - onCreate
06-02 15:46:10.249: D/bug_test_for_login_and_autologin(32004): MUSESBACKGROUNDService - on startComment called
06-02 15:46:20.519: D/bug_test_for_login_and_autologin(32263): MUSESBACKGROUNDService - onCreate
06-02 15:46:20.559: D/bug_test_for_login_and_autologin(32263): MUSESBACKGROUNDService - on startComment called
06-02 15:46:30.704: D/bug_test_for_login_and_autologin(32418): MUSESBACKGROUNDService - onCreate
06-02 15:46:30.764: D/bug_test_for_login_and_autologin(32418): MUSESBACKGROUNDService - on startComment called
06-02 15:46:40.809: D/bug_test_for_login_and_autologin(32653): MUSESBACKGROUNDService - onCreate
06-02 15:46:40.824: D/bug_test_for_login_and_autologin(32653): MUSESBACKGROUNDService - on startComment called
06-02 15:46:50.864: D/bug_test_for_login_and_autologin(32672): MUSESBACKGROUNDService - onCreate
06-02 15:46:50.879: D/bug_test_for_login_and_autologin(32672): MUSESBACKGROUNDService - on startComment called
06-02 15:47:00.919: D/bug_test_for_login_and_autologin(32712): MUSESBACKGROUNDService - onCreate
06-02 15:47:00.934: D/bug_test_for_login_and_autologin(32712): MUSESBACKGROUNDService - on startComment called
06-02 15:47:10.974: D/bug_test_for_login_and_autologin(32746): MUSESBACKGROUNDService - onCreate
06-02 15:47:10.994: D/bug_test_for_login_and_autologin(32746): MUSESBACKGROUNDService - on startComment called
06-02 15:47:21.029: D/bug_test_for_login_and_autologin(317): MUSESBACKGROUNDService - onCreate
06-02 15:47:21.044: D/bug_test_for_login_and_autologin(317): MUSESBACKGROUNDService - on startComment called
06-02 15:47:26.434: D/bug_test_for_login_and_autologin(335): MUSESBACKGROUNDService - onCreate
06-02 15:47:26.449: D/bug_test_for_login_and_autologin(335): MUSESBACKGROUNDService - on startComment called
06-02 15:47:36.489: D/bug_test_for_login_and_autologin(474): MUSESBACKGROUNDService - onCreate
06-02 15:47:36.504: D/bug_test_for_login_and_autologin(474): MUSESBACKGROUNDService - on startComment called
06-02 15:47:46.564: D/bug_test_for_login_and_autologin(951): MUSESBACKGROUNDService - onCreate
06-02 15:47:46.589: D/bug_test_for_login_and_autologin(951): MUSESBACKGROUNDService - on startComment called
06-02 15:47:56.629: D/bug_test_for_login_and_autologin(976): MUSESBACKGROUNDService - onCreate
06-02 15:47:56.644: D/bug_test_for_login_and_autologin(976): MUSESBACKGROUNDService - on startComment called
06-02 15:48:08.744: D/bug_test_for_login_and_autologin(1902): MUSESBACKGROUNDService - onCreate
06-02 15:48:08.764: D/bug_test_for_login_and_autologin(1902): MUSESBACKGROUNDService - on startComment called

**Comment by ChristophStanik** [comment]
cannot reproduce this on HTC one 7 and Nexus 4
