### ISSUE TITLE
Reconnect to server does not work

### ISSUE THREAD

**Issue by mrburvall** [MusesProject/MusesClient#4]
Description:
If network connection is disabled, status becomes offline, but when network is enabled again the status does not become ONLINE.

Reproduce:
Login with Server available. 
Check that status is ONLINE in a popup.
Disable WiFi (Wait >5 s)
Check that status is OFFLINE in a popup.
Enable WiFi (Wait > 5s)
Check the status! Should be ONLINE!

Work Around: NA

**Comment by yasali** [comment]
This issue is been fixed, poll timeout was not set in the cleint.
