### ISSUE TITLE
No action type 

### ISSUE THREAD

**Issue by mrburvall** [MusesProject/MusesClient#5]
Description:
I see in class DevicePolicyHelper.java:275, no action type is added. 
We have made changes in the Action table and a new column is been added called
action type.
This results in that no feedback is shown. (Or always granted)
 
Version: 2015-01-16 (7cb0f9fcbc) 

Logs: See email from Yasir 2015-01-16 14:03

Reproduce: Disable screen lock. 

Work Around: No

Solution:

**Comment by yasali** [comment]
@szamarripa 
Is this already fixed, can we close this?

**Comment by szamarripa** [comment]
This was fixed in previous versions.
