### ISSUE TITLE
MUSES Service restarts?

### ISSUE THREAD

**Issue by mrburvall** [MusesProject/MusesClient#6]
Description:
MUSES Started toast appears when mobile is activated from screen off mode.
This happens "sometimes". It seems the service is restarted. 

Version: 2015-01-19

Logs: "MUSES started" toast.

Reproduce: Let MUSES run on the mobile. 

Work Around: 
Needs to investigate what the effect of this is. Could it happen that it doesn't restart?

Solution: 
1. Remove Toast atleast in silent mode!
2. Does this cause other problems?

**Comment by ChristophStanik** [comment]
Toasts removed. They were shown whenever the background service was restarted. This shouldn't cause any serious problem.
