### ISSUE TITLE
No pop-up shown to user after receiving decisions

### ISSUE THREAD

**Issue by yasali** [MusesProject/MusesClient#7]
Description:
After making changes after the Brussels demo, we are still not showing the 
pop-ups to the user. 
According to logs we are receiving decision from server but still no decision 
shown to user.

Version: 2015-01-19:

Work around:
Most likely the problem is between the decision maker and the GUI. 

Solution:
Please add!

**Comment by ChristophStanik** [comment]
This is already solved
