### ISSUE TITLE
Login screen shows login when logged in

### ISSUE THREAD

**Issue by mrburvall** [MusesProject/MusesClient#9]
Description:
Login screen in GUI, sometimes show the top login text, but still the logout button.

Version: Beta release version 4

Logs: 
![screenshot_2015-02-02-22-25-29](https://cloud.githubusercontent.com/assets/5381985/6015902/89253eac-ab7a-11e4-9470-6cb17a53f1eb.png)

Reproduce: 
Run it for a while, open GUI

Work Around: N/A

Solution: 
Set text when setting button!

**Comment by mrburvall** [comment]
Check UserContextEventHandler.getInstance().isUserAuthenticated();

**Comment by mrburvall** [comment]
Fixed

**Comment by unintendedbear** [comment]
Remember that is better to close issues via commits. Simply include "closes #commitnumber" when making the commit which fixes the issue.
